language: perl
perl:
   - 5.19
   - 5.18
   - 5.16
   - 5.14
   - 5.12
   - 5.10
   - 5.8

before_install:
   - '(echo yes; echo o conf prerequisites_policy follow;echo o conf commit) | cpan'

notifications:
   irc:
      channels:
         - irc.freenode.org#chupei.pm
